server:
  port: 8080

# 数据源配置
datasource:
  driverName: mysql
  host: 172.18.23.38
  port: "3306"
  dbname: gin_temp
  username: root
  password: 123456
  charset: utf8
  sslmode: disable
  loc: Asia/Shanghai